vocab_size: 18006
context_length: 256
d_model: 512
d_ff: 1344
rope_theta: 10000
n_layers: 4
n_heads: 16
image_d_model: 192
num_experts: 16
img_size: 256
patch_size: 16
lr: 0.0001
lr_warmup: 0.0001
alpha_max: 0.0003
alpha_min: 0.0000003
T_w: 1000
T_c: 15000 
beta1: 0.9
beta2: 0.999
eps: 0.00001
weight_decay: 0.001
batch_size: 16
device: "cuda"
dtype: "float32"
log_interval: 100
ckpt_path: 'exp1_lr001_eps15_wd001.pth'
train_data: "data"
val_data: "data"
max_iters: 20000
prefix_name_experiment: 'exp1_lr001_eps15_nlayers4_nheads16_bSize16_wd001'